# Generated by Django 4.2.9 on 2024-09-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_management', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='end_time',
        ),
        migrations.AddField(
            model_name='sport',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/sport_banners/'),
        ),
        migrations.AddField(
            model_name='sport',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/sport_videos/'),
        ),
        migrations.AddField(
            model_name='spouncer',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prizes_first',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prizes_second',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prizes_third',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
    ]
