# Generated by Django 4.2.9 on 2024-09-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_management', '0003_remove_match_end_time_sport_banner_sport_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='earnings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
