# Generated by Django 4.2.9 on 2024-09-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility_management', '0003_facility_image1_facility_image2_facility_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='facility',
        ),
    ]
