# Generated by Django 4.2.9 on 2024-09-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_management', '0004_remove_booking_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainance',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sport',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/sport_banners/'),
        ),
    ]
