# Generated by Django 4.2.9 on 2024-09-27 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility_management', '0005_maintainance_cost_sport_banner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bookingslot',
            unique_together={('start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='booking',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facility_management.facility'),
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='set_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('facility', 'slots', 'booking_date')},
        ),
        migrations.RemoveField(
            model_name='bookingslot',
            name='facility',
        ),
    ]
